#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the bonAppetit function below.
def bonAppetit(bill, k, b):
    total = 0
    for a in range(0, len(bill)):
        if(a!=k):
            total = total + bill[a]
    
    if(abs(total/2) == b):
        print("Bon Appetit")
    else:
        print(b-int(total/2))

if __name__ == '__main__':
    nk = input().rstrip().split()

    n = int(nk[0])

    k = int(nk[1])

    bill = list(map(int, input().rstrip().split()))

    b = int(input().strip())

    bonAppetit(bill, k, b)
