#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the divisibleSumPairs function below.
def divisibleSumPairs(n, k, ar):
    count = 0
    listU = []
    for a in range(0, len(ar)):
        for b in range(0, len(ar)):
            if((ar[a]+ar[b])%k==0 and [a, b] not in listU and [b, a] not in listU and a!=b):
                count = count + 1
                print(a,b)
                listU.append([a, b])
                listU.append([b, a])

    return count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    ar = list(map(int, input().rstrip().split()))

    result = divisibleSumPairs(n, k, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
